# Generated by Django 4.1.7 on 2023-04-24 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="recipe",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="recipe.recipe",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favoriterecipe",
            unique_together={("user", "recipe")},
        ),
    ]
