# Generated by Django 4.1.7 on 2023-05-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_ingredient_recipe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.CharField(max_length=255),
        ),
    ]
