# Generated by Django 4.1.7 on 2023-05-16 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0004_alter_ingredient_quantity_alter_recipe_cooking_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="recipe",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="recipe.recipe",
            ),
        ),
    ]
