# Generated by Django 4.1.7 on 2023-05-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0005_alter_ingredient_recipe"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
