# Generated by Django 4.2 on 2023-04-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DemoDjango", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field1", models.CharField(max_length=100)),
                ("field2", models.CharField(max_length=40)),
            ],
            options={
                "ordering": ["field1"],
            },
        ),
    ]
